#apiVersion: v1
#kind: Service
#metadata:
#  name: backend-load-balancer
#spec:
#  type: LoadBalancer
#  selector:
#    app: backend
#  ports:
#    - protocol: TCP
#      port: 80
#      targetPort: 8080
#      name: http
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service-public
spec:
  type: NodePort
  selector:
    app: backend
  ports:
  - protocol: TCP
    port: 8080
    nodePort: 30088
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  selector:
    matchLabels:
      app: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: "andiburgr/distance-warner:latest"
        env:
        - name: "spring.datasource.url"
          value: "jdbc:mariadb://db-service:6033/distance-warner"
        - name: "logging.level.root"
          value: "INFO"